/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Address;
import Model.ContactInfo;
import Model.Person;

/**
 *
 * @author Yue
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private Person person;// properity 
    
    public MainJFrame() {
        initComponents();
        
        this.person = new Person();//new object
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        creatPanel = new javax.swing.JPanel();
        fieldName1 = new javax.swing.JTextField();
        fieldCurrentStreet = new javax.swing.JTextField();
        saveButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldLastName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fieldNuid = new javax.swing.JTextField();
        fieldCollegeName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fieldAptNum = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fieldCurrentCity = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldCurrentZip = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fieldPermanentStreet = new javax.swing.JTextField();
        fieldPermanentApt = new javax.swing.JTextField();
        fieldPermanentCity = new javax.swing.JTextField();
        fieldPermanentZip = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fieldOfficePhone = new javax.swing.JTextField();
        fieldOfficeEmail = new javax.swing.JTextField();
        fieldPersonalPhone = new javax.swing.JTextField();
        fieldPersonalEmail = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        userPanel = new javax.swing.JPanel();
        viewName2 = new javax.swing.JLabel();
        viewStreet2 = new javax.swing.JLabel();
        viewLastName = new javax.swing.JLabel();
        viewAptNum = new javax.swing.JLabel();
        viewNuid = new javax.swing.JLabel();
        viewCollegeName = new javax.swing.JLabel();
        viewCurrentCity = new javax.swing.JLabel();
        viewCurrentZip = new javax.swing.JLabel();
        viewPermanentStreet = new javax.swing.JLabel();
        viewPermanentApt = new javax.swing.JLabel();
        viewPermanentCity = new javax.swing.JLabel();
        viewPermanentZip = new javax.swing.JLabel();
        viewOfficePhone = new javax.swing.JLabel();
        viewOfficeEmail = new javax.swing.JLabel();
        viewPersonalPhone = new javax.swing.JLabel();
        viewPersonalEmail = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        creatPanel.setBackground(new java.awt.Color(255, 204, 204));

        fieldName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldName1ActionPerformed(evt);
            }
        });

        saveButton1.setText("SAVE");
        saveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("First Name");

        jLabel4.setText("Street");

        jLabel5.setText("Last Name");

        jLabel1.setText("NUID:");

        fieldNuid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNuidActionPerformed(evt);
            }
        });

        jLabel6.setText("College:");

        jLabel7.setText("Apt No.");

        fieldCurrentCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCurrentCityActionPerformed(evt);
            }
        });

        jLabel2.setText("City");

        jLabel8.setText("Zip Code");

        jLabel9.setText("Current Address");

        jLabel10.setText("Permanent Address");

        fieldPermanentApt.setText("  ");
        fieldPermanentApt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPermanentAptActionPerformed(evt);
            }
        });

        jLabel11.setText("Phone");

        jLabel12.setText("Email");

        jLabel13.setText("Office");

        jLabel14.setText("Personal");

        fieldOfficeEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldOfficeEmailActionPerformed(evt);
            }
        });

        jLabel29.setText("Please fill the form:");

        javax.swing.GroupLayout creatPanelLayout = new javax.swing.GroupLayout(creatPanel);
        creatPanel.setLayout(creatPanelLayout);
        creatPanelLayout.setHorizontalGroup(
            creatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creatPanelLayout.createSequentialGroup()
                .addGroup(creatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(creatPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(creatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(creatPanelLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fieldPermanentStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creatPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(38, 38, 38)))
                        .addGroup(creatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(creatPanelLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel12))
                            .addGroup(creatPanelLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(creatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldOfficeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldPersonalEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(creatPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(creatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(40, 40, 40)
                        .addGroup(creatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldPersonalPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldOfficePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(creatPanelLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(saveButton1))
                    .addGroup(creatPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(creatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(creatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(creatPanelLayout.createSequentialGroup()
                                    .addComponent(fieldPermanentApt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(fieldPermanentCity, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(creatPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(30, 30, 30)
                                    .addGroup(creatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(creatPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(36, 36, 36)
                                            .addComponent(jLabel7))
                                        .addGroup(creatPanelLayout.createSequentialGroup()
                                            .addComponent(fieldCurrentStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(fieldAptNum, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(19, 19, 19)
                                    .addComponent(fieldCurrentCity, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(creatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addGroup(creatPanelLayout.createSequentialGroup()
                                    .addGroup(creatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel1))
                                    .addGap(18, 18, 18)
                                    .addGroup(creatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(creatPanelLayout.createSequentialGroup()
                                            .addComponent(fieldNuid, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(fieldCollegeName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(creatPanelLayout.createSequentialGroup()
                                            .addComponent(fieldName1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel5)
                                            .addGap(18, 18, 18)
                                            .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(18, 18, 18)
                        .addGroup(creatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(creatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fieldCurrentZip, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldPermanentZip, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)))
                    .addGroup(creatPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel29)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        creatPanelLayout.setVerticalGroup(
            creatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creatPanelLayout.createSequentialGroup()
                .addComponent(jLabel29)
                .addGap(10, 10, 10)
                .addGroup(creatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldNuid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCollegeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(creatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(19, 19, 19)
                .addGroup(creatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addGroup(creatPanelLayout.createSequentialGroup()
                        .addGroup(creatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(creatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldCurrentStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldAptNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldCurrentCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldCurrentZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(creatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(fieldPermanentStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldPermanentApt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldPermanentCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldPermanentZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(creatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(creatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(fieldOfficePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldOfficeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(creatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(fieldPersonalPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldPersonalEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(saveButton1)
                .addGap(22, 22, 22))
        );

        jSplitPane1.setLeftComponent(creatPanel);

        userPanel.setBackground(new java.awt.Color(255, 255, 153));

        viewName2.setText("Name");

        viewStreet2.setText("Street");

        viewLastName.setText("last Name");

        viewAptNum.setText("Apt No.");

        viewNuid.setText("NUID");

        viewCollegeName.setText("College");

        viewCurrentCity.setText("City");

        viewCurrentZip.setText("Zip");

        viewPermanentStreet.setText("Street2");

        viewPermanentApt.setText("apt2");

        viewPermanentCity.setText("City2");

        viewPermanentZip.setText("Zip2");

        viewOfficePhone.setText("Office Phone");

        viewOfficeEmail.setText("Office Email");

        viewPersonalPhone.setText("personal phone");

        viewPersonalEmail.setText("personal email");

        jLabel15.setText("NUID:");

        jLabel16.setText("College Name:");

        jLabel17.setText("First Name:");

        jLabel18.setText("Last Name:");

        jLabel19.setText("Current Address:");

        jLabel20.setText("Permanent Address:");

        jLabel21.setText("Street");

        jLabel22.setText("Apt No.");

        jLabel23.setText("City");

        jLabel24.setText("Zip Code");

        jLabel25.setText("Office:");

        jLabel26.setText("Personal:");

        jLabel27.setText("Phone");

        jLabel28.setText("Email");

        jLabel30.setText("Husky Card Info:");

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewNuid)
                    .addComponent(viewName2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewCollegeName)
                    .addComponent(viewLastName))
                .addGap(102, 102, 102))
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)))
                            .addGroup(userPanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel25))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viewOfficePhone)
                                    .addComponent(viewPersonalPhone)
                                    .addComponent(jLabel27))))
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(userPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel22))
                                    .addGroup(userPanelLayout.createSequentialGroup()
                                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(viewStreet2)
                                            .addComponent(viewPermanentStreet))
                                        .addGap(37, 37, 37)
                                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(viewAptNum)
                                            .addComponent(viewPermanentApt))))
                                .addGap(34, 34, 34)
                                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(userPanelLayout.createSequentialGroup()
                                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(viewCurrentCity)
                                            .addComponent(viewPermanentCity))
                                        .addGap(37, 37, 37)
                                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(viewPermanentZip)
                                            .addComponent(viewCurrentZip)))
                                    .addGroup(userPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel24))))
                            .addGroup(userPanelLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(viewOfficeEmail)))))
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(viewPersonalEmail))
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel30)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addGap(7, 7, 7)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewNuid)
                    .addComponent(viewCollegeName)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewName2)
                    .addComponent(viewLastName)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addGap(14, 14, 14)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewStreet2)
                    .addComponent(viewAptNum)
                    .addComponent(viewCurrentCity)
                    .addComponent(viewCurrentZip)
                    .addComponent(jLabel19))
                .addGap(27, 27, 27)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewPermanentStreet)
                    .addComponent(viewPermanentApt)
                    .addComponent(viewPermanentCity)
                    .addComponent(viewPermanentZip)
                    .addComponent(jLabel20))
                .addGap(19, 19, 19)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewOfficePhone)
                    .addComponent(viewOfficeEmail)
                    .addComponent(jLabel25))
                .addGap(27, 27, 27)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewPersonalPhone)
                    .addComponent(viewPersonalEmail)
                    .addComponent(jLabel26))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(userPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldName1ActionPerformed

    private void saveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButton1ActionPerformed
        // TODO add your handling code here:
        String nuid = fieldNuid.getText();
        String collegeName =fieldCollegeName.getText();
        String firstName = fieldName1.getText(); //use the fieldName variable to get the text
        String lastName = fieldLastName.getText();
        
        String currentStreet = fieldCurrentStreet.getText();
        String currentAptNum = fieldAptNum.getText();
        String currentCity = fieldCurrentCity.getText();
        String currentZip = fieldCurrentZip.getText();
        
        String street2 = fieldPermanentStreet.getText();
        String permanentAptNum = fieldPermanentApt.getText();
        String permanentCity = fieldPermanentCity.getText();
        String permanentZip = fieldPermanentZip.getText();
        
        String officePhone = fieldOfficePhone.getText();
        String officeEmail = fieldOfficeEmail.getText();
        
        String personalPhone = fieldPersonalPhone.getText();
        String personalEmail = fieldPersonalEmail.getText();
        
        
        this.person.setNUID(nuid);
        this.person.setCollegeName(collegeName);
        this.person.setFirstName(firstName);
        this.person.setLastName(lastName);
        
        Address currentAddress = this.person.getCurrentAddress();//get the person object's address
        currentAddress.setStreetName(currentStreet);
        currentAddress.setAptNum(currentAptNum);
        currentAddress.setCity(currentCity);
        currentAddress.setZipCode(currentZip);
        
        Address permanentAddress = this.person.getPermanentAddress();
        permanentAddress.setStreetName(street2);
        permanentAddress.setAptNum(permanentAptNum);
        permanentAddress.setCity(permanentCity);
        permanentAddress.setZipCode(permanentZip);
        
        ContactInfo officeInfo = this.person.getOfficeContactInfo();
        officeInfo.setPhone(officePhone);
        officeInfo.setEmailID(officeEmail);
        
        ContactInfo personalInfo = this.person.getPersonalContactInfo();
        personalInfo.setPhone(personalPhone);
        personalInfo.setEmailID(personalEmail);
        
        
        display();
        
        
        
    }//GEN-LAST:event_saveButton1ActionPerformed

    private void fieldCurrentCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCurrentCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCurrentCityActionPerformed

    private void fieldNuidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNuidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNuidActionPerformed

    private void fieldOfficeEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldOfficeEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldOfficeEmailActionPerformed

    private void fieldPermanentAptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPermanentAptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPermanentAptActionPerformed

    private void display(){
        viewNuid.setText(this.person.getNUID());
        viewCollegeName.setText(this.person.getCollegeName());
        viewName2.setText(this.person.getFirstName());
        viewLastName.setText(this.person.getLastName());
        
        viewStreet2.setText(this.person.getCurrentAddress().getStreetName());
        viewAptNum.setText(this.person.getCurrentAddress().getAptNum());
        viewCurrentCity.setText(this.person.getCurrentAddress().getCity());
        viewCurrentZip.setText(this.person.getCurrentAddress().getZipCode());

        viewPermanentStreet.setText(this.person.getPermanentAddress().getStreetName());
        viewPermanentApt.setText(this.person.getPermanentAddress().getAptNum());
        viewPermanentCity.setText(this.person.getCurrentAddress().getCity());
        viewPermanentZip.setText(this.person.getCurrentAddress().getZipCode());
        
        viewOfficePhone.setText(this.person.getOfficeContactInfo().getPhone());
        viewOfficeEmail.setText(this.person.getOfficeContactInfo().getEmailID());
        
        viewPersonalPhone.setText(this.person.getPersonalContactInfo().getPhone());
        viewPersonalEmail.setText(this.person.getPersonalContactInfo().getEmailID());
        
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel creatPanel;
    private javax.swing.JTextField fieldAptNum;
    private javax.swing.JTextField fieldCollegeName;
    private javax.swing.JTextField fieldCurrentCity;
    private javax.swing.JTextField fieldCurrentStreet;
    private javax.swing.JTextField fieldCurrentZip;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldName1;
    private javax.swing.JTextField fieldNuid;
    private javax.swing.JTextField fieldOfficeEmail;
    private javax.swing.JTextField fieldOfficePhone;
    private javax.swing.JTextField fieldPermanentApt;
    private javax.swing.JTextField fieldPermanentCity;
    private javax.swing.JTextField fieldPermanentStreet;
    private javax.swing.JTextField fieldPermanentZip;
    private javax.swing.JTextField fieldPersonalEmail;
    private javax.swing.JTextField fieldPersonalPhone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton saveButton1;
    private javax.swing.JPanel userPanel;
    private javax.swing.JLabel viewAptNum;
    private javax.swing.JLabel viewCollegeName;
    private javax.swing.JLabel viewCurrentCity;
    private javax.swing.JLabel viewCurrentZip;
    private javax.swing.JLabel viewLastName;
    private javax.swing.JLabel viewName2;
    private javax.swing.JLabel viewNuid;
    private javax.swing.JLabel viewOfficeEmail;
    private javax.swing.JLabel viewOfficePhone;
    private javax.swing.JLabel viewPermanentApt;
    private javax.swing.JLabel viewPermanentCity;
    private javax.swing.JLabel viewPermanentStreet;
    private javax.swing.JLabel viewPermanentZip;
    private javax.swing.JLabel viewPersonalEmail;
    private javax.swing.JLabel viewPersonalPhone;
    private javax.swing.JLabel viewStreet2;
    // End of variables declaration//GEN-END:variables
}
