/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdminWorkArea;

import AppSystem.AppSystem;
import AppSystem.UserAccount;
import Library.Librarian;
import Services.RentalRequest;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yue
 */
public class RentalRequestManagementJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RentalRequestManagementJPanel
     */
    private AppSystem appSystem;
    private UserAccount useraccount;
    DefaultTableModel tableModel;
    
    public RentalRequestManagementJPanel() {
        initComponents();
    }
    
    RentalRequestManagementJPanel(AppSystem appSystem, UserAccount useraccount) {
        initComponents();

        this.appSystem = appSystem;
        this.useraccount = useraccount;
        this.tableModel = (DefaultTableModel) jTable1.getModel();

        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RequestID", "Customer", "Librarian"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void populate() {
        
        tableModel.setRowCount(0);
        for (RentalRequest r : this.appSystem.getLibrarian().getLibrarianRequestList()) {

            Object[] row = new Object[3];

            row[0] = r;
            row[1] = r.getCustomer().getPersonID();
            row[2] = r.getLibrarian().getPersonID();

            tableModel.addRow(row);
        }

    }

//    public void populateDp() {
//
//        jComboBox1.removeAllItems();
//
//        Librarian l = this.appSystem.getLibrarian();
//            jComboBox1.addItem(l);
//        
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
