/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import Model.Customer;
import Model.DeliveryPackage;
import Model.Product;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Yue
 */

public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private DeliveryPackage delPackage;
    private Boolean validation = false;
    public CreateJPanel() {
        initComponents();
        
        
    }
    
    public CreateJPanel(DeliveryPackage deliverPackage){ //new constructor 
        initComponents();
        this.delPackage = deliverPackage;
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        packageIdTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        productIdTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        productPriceTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        productNameTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        customerFullNameTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        packageWeightTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        customerIdTextField = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        SaveBtn2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        jLabel1.setText("Package Id:");

        jLabel2.setText("Product Id:");

        jLabel3.setText("Product price:");

        jLabel4.setText("Product name:");

        jLabel6.setText("Customer full name:");

        customerFullNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                customerFullNameTextFieldFocusLost(evt);
            }
        });

        jLabel7.setText("Package weight:");

        jLabel8.setText("Customer ID:");

        saveBtn.setText("SAVE");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        SaveBtn2.setText("SAVE PRODUCT");
        SaveBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtn2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Create your package");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(48, 48, 48)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(customerIdTextField))
                            .addComponent(customerFullNameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SaveBtn2)
                            .addComponent(saveBtn)))
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(productNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                    .addComponent(productPriceTextField)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(47, 47, 47)
                                .addComponent(productIdTextField))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(28, 28, 28)
                            .addComponent(packageWeightTextField))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(47, 47, 47)
                            .addComponent(packageIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(packageIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(packageWeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(customerFullNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(customerIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBtn))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(productIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(productNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(productPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveBtn2))
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        
        //DeliveryPackage delPackage = new DeliveryPackage();
        
        String id = packageIdTextField.getText();
        String weight = packageWeightTextField.getText();
        
        String customerName = customerFullNameTextField.getText();
        String customerId = customerIdTextField.getText();
        
        this.delPackage.setPackageId(Integer.valueOf(id));
        this.delPackage.setPackageWeight(Double.valueOf(weight));
        
        Customer customer = this.delPackage.getCustomer();
        customer.setCustomerID(Integer.valueOf(customerId));
        customer.setFullName(customerName);
        
        if(validation){
            JOptionPane.showMessageDialog(null, "Please fill all the fields!");
        } else {
            JOptionPane.showMessageDialog(null, "Saved!");
        }
        

        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void SaveBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtn2ActionPerformed
        // TODO add your handling code here:
        String productId = productIdTextField.getText();
        String productName = productNameTextField.getText();
        String productPrice = productPriceTextField.getText();
        
//        ArrayList<Product> productList = this.delPackage.getProductList();
        Product product = this.delPackage.createProduct(Integer.valueOf(productId), productName, Double.valueOf(productPrice));
//        productList.add(product);
        JOptionPane.showMessageDialog(null, "Product added!");

        
    }//GEN-LAST:event_SaveBtn2ActionPerformed

    private void customerFullNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerFullNameTextFieldFocusLost
        // TODO add your handling code here:
        
        System.out.println(customerFullNameTextField.getText() + " -- the customer name");
        String name = customerFullNameTextField.getText();
        
        if(name.isEmpty()){
            this.validation = true;
        } else {
            this.validation  = false;
            
        }
    }//GEN-LAST:event_customerFullNameTextFieldFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveBtn2;
    private javax.swing.JTextField customerFullNameTextField;
    private javax.swing.JTextField customerIdTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField packageIdTextField;
    private javax.swing.JTextField packageWeightTextField;
    private javax.swing.JTextField productIdTextField;
    private javax.swing.JTextField productNameTextField;
    private javax.swing.JTextField productPriceTextField;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
